name: ecosysteme_logistique
channels:
  - conda-forge
  - defaults
dependencies:
  - conda>=4.10.2
  - conda-package-handling>=1.7.3
  - descartes=1.1.0
  - docutils=0.16
  - fiona=1.8.13.post1
  - folium>=0.12.0
  - freetype=2.10.4
  - freexl=1.0.6
  - gast=0.4.0
  - gdal=3.0.2
  - geographiclib=1.50
  - geopandas>=0.8.1
  - geopy=2.1.0
  - geos=3.8.0
  - geotiff=1.5.1
  - ipython_genutils=0.2.0
  - itsdangerous=2.0.1
  - jsonschema=3.2.0
  - jupyter_core=4.7.1
  - kealib=1.4.7
  - matplotlib-base=3.3.4
  - mkl_random=1.1.1
  - multidict=5.1.0
  - mumps-seq=5.2.1
  - munch=2.5.0
  - nbstripout=0.4.0
  - numba>=0.53.0
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openjpeg=2.3.0
  - openmp=5.0.0
  - openssl=1.1.1k
  - opt_einsum=3.3.0
  - pandas=1.1.5
  - pcre=8.44
  - pip>=21.1.2
  - proj=6.2.1
  - protobuf=3.14.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycosat=0.6.3
  - pycparser=2.20
  - pyjwt=2.1.0
  - pyopenssl=20.0.1
  - pyparsing=2.4.7
  - pyproj=2.6.1.post1
  - pyqt=5.9.2
  - pyreadline=2.1
  - pyrsistent=0.17.3
  - pyshp=2.1.3
  - pysocks=1.7.1
  - python=3.8.10
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - pywin32=227
  - pyyaml=5.4.1
  - qt=5.9.7
  - requests=2.25.1
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - rtree=0.9.7
  - ruamel_yaml=0.15.100
  - scipy>=1.6.2
  - seaborn>=0.11.1
  - setuptools>=52.0.0
  - shapely>=1.7.1
  - sip=4.19.13
  - six=1.16.0
  - snowballstemmer=2.1.0
  - sphinx>=4.0.2
  - sphinx-automodapi
  - sphinxcontrib-applehelp
  - sphinxcontrib-devhelp
  - sphinxcontrib-htmlhelp
  - sphinxcontrib-jsmath
  - sphinxcontrib-qthelp
  - sphinxcontrib-serializinghtml

  - pip:
    - bleach==3.2.1
    - breathe==4.30.0
    - commonmark==0.9.1

    - cython==0.29.21
    - decorator==4.4.2
    - defusedxml==0.6.0
    - ijson==3.1.4
    - ipykernel==5.4.2
    - ipython==7.19.0
    - ipywidgets==7.6.2
    - isort==5.7.0
    - jedi==0.18.0
    - jinja2==2.11.2
    - joblib==1.0.1
    - json5==0.9.5
    - jupyter==1.0.0
    - jupyter-client==6.1.7
    - jupyter-console==6.2.0
    - jupyter-core==4.7.0
    - jupyter-server==1.8.0
    - m2r==0.2.1
    - m2r2==0.2.8
    - matplotlib>=3.3.3
    - mccabe==0.6.1
    - mistune==0.8.4
    - mpmath==1.1.0
    - networkx==2.5.1
    - notebook==6.1.6
    - numpy==1.19.3
    - nupy==0.1.1
    - packaging==20.8
    - pdoc3==0.9.2
    - pycallgraph==1.0.1
    - pyqt5==5.15.4
    - pyqt5-qt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyqtwebengine==5.15.4
    - pyqtwebengine-qt5==5.15.2
    - pyspellchecker==0.6.2
    - pytesseract==0.3.7
    - python-engineio==3.13.2
    - python-jsonrpc-server==0.3.4
    - pyzmq==20.0.0
    - qtconsole==5.0.1
    - qtpy==1.9.0
    - rstcheck==3.3.1
    - scikit-learn>=0.24.1

